const DEFAULT_CONTENT_URL='content.default.json';
const CONFIG=window.ADS_CONFIG||{};let siteContent={};
async function loadContent(){try{siteContent=await(await fetch(DEFAULT_CONTENT_URL,{cache:'no-store'})).json()}catch(e){console.error('Não foi possível carregar content.default.json',e);siteContent={}}applyContent()}
function cssDecls(obj){const out=[];Object.entries(obj||{}).forEach(([k,v])=>{if(k==='__raw'||v===''||v==null)return;out.push(`${k}:${v}!important`)});if(obj&&obj.__raw)out.push(obj.__raw.trim());return out.join(';')}
function applyProductionStyles(){let style=document.getElementById('adsProductionStyles');if(!style){style=document.createElement('style');style.id='adsProductionStyles';document.head.appendChild(style)}let css='';Object.entries(siteContent.__styles||{}).forEach(([selector,devices])=>{const d=cssDecls(devices.desktop);if(d)css+=`${selector}{${d}}\n`;const t=cssDecls(devices.tablet);if(t)css+=`@media (max-width:980px){${selector}{${t}}}\n`;const m=cssDecls(devices.mobile);if(m)css+=`@media (max-width:640px){${selector}{${m}}}\n`});style.textContent=css}
function applyContent(){document.querySelectorAll('[data-edit]').forEach(el=>{const k=el.dataset.edit;if(siteContent[k]!=null)el.textContent=siteContent[k]});applyProductionStyles()}
function track(event,params={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...params,page_type:'institutional',service:'general'})}
function openModal(id,source){const m=document.getElementById(id);if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';track('form_open',{form_id:id==='diagnosticModal'?'diagnostico_geral':'whatsapp_quick',source_cta:source||'unknown'})}
function closeModals(){document.querySelectorAll('.modal.open').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')});document.body.style.overflow=''}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action){const locationName=action.dataset.trackLocation||'unknown';const label=action.innerText.trim().toLowerCase().replace(/\s+/g,'_').slice(0,80);track('cta_click',{cta_location:locationName,cta_text:label,cta_type:'primary'});if(action.dataset.action==='diagnostic')openModal('diagnosticModal',locationName);if(action.dataset.action==='quick')openModal('quickModal',locationName)}if(e.target.matches('[data-close-modal]'))closeModals()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
function captureAttribution(){const url=new URL(location.href);const keys=['utm_source','utm_medium','utm_campaign','utm_content','utm_term'];const current={landing_url:location.href,landing_path:location.pathname};keys.forEach(k=>{if(url.searchParams.get(k))current[k]=url.searchParams.get(k)});if(!localStorage.getItem('ads_first_touch'))localStorage.setItem('ads_first_touch',JSON.stringify(current));localStorage.setItem('ads_last_touch',JSON.stringify(current))}
function buildPayload(form,leadType){const data=Object.fromEntries(new FormData(form).entries());return{...data,lead_type:leadType,page:location.href,first_touch:JSON.parse(localStorage.getItem('ads_first_touch')||'{}'),last_touch:JSON.parse(localStorage.getItem('ads_last_touch')||'{}'),created_at:new Date().toISOString()}}
async function sendWebhook(payload){if(!CONFIG.leadWebhook)return false;try{const r=await fetch(CONFIG.leadWebhook,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});return r.ok||r.type==='opaque'}catch(e){return false}}
function whatsappNumber(){return String(CONFIG.whatsappNumber||siteContent['settings.whatsapp_number']||'').replace(/\D/g,'')}
function openWhatsapp(payload,kind){const number=whatsappNumber();if(!number)return false;const base=siteContent['settings.whatsapp_message']||'Olá! Vim pelo site da ADS & ADS.';const lines=[base,`Nome: ${payload.name||''}`];if(payload.company)lines.push(`Empresa: ${payload.company}`);if(payload.email)lines.push(`E-mail: ${payload.email}`);if(payload.phone)lines.push(`Telefone: ${payload.phone}`);if(payload.challenge)lines.push(`Desafio: ${payload.challenge}`);window.location.href=`https://wa.me/${number}?text=${encodeURIComponent(lines.join('\n'))}`;track('whatsapp_click',{placement:kind,lead_type:payload.lead_type});return true}
function bindFormStart(id){const f=document.getElementById(id);if(!f)return;f.addEventListener('focusin',()=>{if(!f.dataset.started){f.dataset.started='1';track('form_start',{form_id:f.dataset.formId})}})}bindFormStart('diagnosticForm');bindFormStart('quickForm');
const diagnosticForm=document.getElementById('diagnosticForm');if(diagnosticForm)diagnosticForm.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const status=form.querySelector('.form-status');const payload=buildPayload(form,'diagnostic');status.textContent='Enviando...';track('form_submit',{form_id:form.dataset.formId,lead_type:'diagnostic'});const saved=await sendWebhook(payload);if(saved){track('generate_lead',{form_id:form.dataset.formId,lead_type:'diagnostic'});status.textContent='Recebido. Vamos analisar o seu cenário.';setTimeout(closeModals,1200)}else if(openWhatsapp(payload,'diagnostic_fallback')){track('generate_lead',{form_id:form.dataset.formId,lead_type:'diagnostic_whatsapp'});status.textContent='Abrindo o WhatsApp...'}else{status.textContent='A captação ainda não foi configurada. Preencha leadWebhook ou whatsappNumber em site.config.js.'}});
const quickForm=document.getElementById('quickForm');if(quickForm)quickForm.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const status=form.querySelector('.form-status');const payload=buildPayload(form,'whatsapp');status.textContent='Preparando contato...';track('form_submit',{form_id:form.dataset.formId,lead_type:'whatsapp'});const saved=await sendWebhook(payload);if(saved)track('generate_lead',{form_id:form.dataset.formId,lead_type:'whatsapp'});if(openWhatsapp(payload,'quick_form')){if(!saved)track('generate_lead',{form_id:form.dataset.formId,lead_type:'whatsapp_unstored'});status.textContent='Abrindo o WhatsApp...'}else{status.textContent=saved?'Lead salvo. Configure o número do WhatsApp para continuar.':'Configure o webhook ou o número do WhatsApp em site.config.js.'}});
// jelly cursor highlight + click pop
document.querySelectorAll('.jelly').forEach(el=>{el.addEventListener('pointermove',ev=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${((ev.clientX-r.left)/r.width)*100}%`);el.style.setProperty('--my',`${((ev.clientY-r.top)/r.height)*100}%`)});el.addEventListener('click',()=>{el.classList.remove('is-popping');void el.offsetWidth;el.classList.add('is-popping');setTimeout(()=>el.classList.remove('is-popping'),450)})});
// active nav state
const navLinks=[...document.querySelectorAll('.nav a[href^="#"]')];const observed=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${visible.target.id}`))},{rootMargin:'-25% 0px -55% 0px',threshold:[.05,.2,.45]});observed.forEach(s=>io.observe(s))}
// social URLs
const socialMap={instagram:CONFIG.instagramUrl,linkedin:CONFIG.linkedinUrl,youtube:CONFIG.youtubeUrl,email:CONFIG.email?`mailto:${CONFIG.email}`:''};document.querySelectorAll('[data-social]').forEach(a=>{const url=socialMap[a.dataset.social];if(url){a.href=url}else{a.addEventListener('click',e=>e.preventDefault());a.title='Configure este link em site.config.js'}});if(CONFIG.email){const em=document.querySelector('[data-social="email"]');if(em)em.textContent=CONFIG.email}
captureAttribution();loadContent();